---
- name: Get the VPC ID for {{ ec2_name_prefix }}-vpc
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ ec2_name_prefix }}-vpc"
    region: "{{ ec2_region }}"
  register: vpc_net_facts

- name: Get the SG ID for {{ ec2_name_prefix }}-sg
  ec2_group_info:
    filters:
      vpc-id: "{{ vpc_net_facts.vpcs[0].id }}"
      group-name: "{{ ec2_name_prefix }}-sg"
    region: "{{ ec2_region }}"
  register: sg_net_facts

- name: Get the subnet ID for {{ ec2_name_prefix }}-subnet
  ec2_vpc_subnet_info:
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ vpc_net_facts.vpcs[0].id }}"
      "tag:Name": "{{ ec2_name_prefix }}-subnet"
  register: subnet_facts

- name: "Find current, region-specific Windows AMI."
  ec2_ami_info:
    region: "{{ aws_region }}"
    filters:
      name: "{{ ami_name }}"
  register: found_amis

- name: "Set AMI value"
  set_fact:
    win_ami: "{{ found_amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}"
  when: found_amis.images is defined

- name: "Start Windows instances."
  ec2:
    key_name: "ansible-aws-demo"
    region: "{{ aws_region }}"
    image: "{{ win_ami.image_id }}"
    instance_type: "{{ instance_type }}"
    group_id: "{{ sg_net_facts.security_groups[0].group_id }}"
    vpc_subnet_id: "{{ subnet_facts.subnets[0].id }}"
    wait: yes
    wait_timeout: 500
    exact_count: 1
    count_tag:
      count_tag: Name
    instance_tags:
      Name: "{{ instance_tag_name }}"
      Role: "{{ instance_tag_role }}"
      Inventory: "{{ instance_tag_inventory }}"
    user_data: "{{ lookup('template', '{{ role_path }}/templates/userdata.txt.j2') }}"
  register: ec2_result

- name: set public ip
  set_fact:
    public_ip: "{{ ec2_result.instances[0].public_ip }}"

- name: "Wait for WinRM on all hosts."
  wait_for:
    port: 5986
    host: "{{ ec2_result.instances[0].public_ip }}"
    timeout: 300

- name: Show public IP
  debug:
    msg: "{{ ec2_result.instances[0].public_ip }}"

